2024-01-08 08:56:47.248 - INFO - 28944 - azureml.train.automl.run._log_activity:55 - ActivityStarted: GetOutput
2024-01-08 08:56:47.300 - INFO - 28944 - azureml.train.automl.run._log_activity:55 - ActivityStarted: GetOutput
2024-01-08 08:56:47.320 - INFO - 28944 - azureml.train.automl.run._log_activity:55 - ActivityStarted: GetChildren
2024-01-08 08:56:47.434 - INFO - 28944 - azureml.train.automl.run._log_activity:89 - ActivityCompleted: Activity=GetChildren, HowEnded=Success, Duration=113.43[ms]
2024-01-08 08:56:47.480 - INFO - 28944 - azureml.train.automl.run._log_activity:89 - ActivityCompleted: Activity=GetOutput, HowEnded=Success, Duration=179.72[ms]
2024-01-08 08:56:47.480 - INFO - 28944 - azureml.train.automl._model_download_utilities._log_activity:55 - ActivityStarted: DownloadModel
2024-01-08 08:56:53.594 - INFO - 28944 - azureml.automl.runtime.featurization.data_transformer.__init__:190 - Feature sweeping enabled: False
2024-01-08 08:56:53.596 - INFO - 28944 - azureml.automl.runtime.featurization.data_transformer.__init__:191 - Feature sweeping timeout: 86400
2024-01-08 08:56:55.861 - INFO - 28944 - azureml.train.automl._model_download_utilities._log_activity:89 - ActivityCompleted: Activity=DownloadModel, HowEnded=Success, Duration=8381.02[ms]
2024-01-08 08:56:55.864 - INFO - 28944 - azureml.train.automl.run._log_activity:89 - ActivityCompleted: Activity=GetOutput, HowEnded=Success, Duration=8615.9[ms]
2024-01-08 09:15:10.136 - INFO - 36995 - azureml.train.automl.run._log_activity:55 - ActivityStarted: GetOutput
2024-01-08 09:15:10.166 - INFO - 36995 - azureml.train.automl.run._log_activity:55 - ActivityStarted: GetOutput
2024-01-08 09:15:10.190 - INFO - 36995 - azureml.train.automl.run._log_activity:55 - ActivityStarted: GetChildren
2024-01-08 09:15:10.257 - INFO - 36995 - azureml.train.automl.run._log_activity:55 - ActivityStarted: GetChildren
2024-01-08 09:15:10.657 - CRITICAL - 36995 - azureml.train.automl.run.log_traceback:227 - Type: ModelMissing
Class: AutoMLException
Message: AutoMLException:
	Message: Could not find a model with valid score for metric 'accuracy'. Please ensure that at least one run was successfully completed with a valid score for the given metric.
	InnerException: None
	ErrorResponse 
{
    "error": {
        "code": "UserError",
        "message": "Could not find a model with valid score for metric 'accuracy'. Please ensure that at least one run was successfully completed with a valid score for the given metric.",
        "target": "metric",
        "inner_error": {
            "code": "NotFound",
            "inner_error": {
                "code": "ModelMissing"
            }
        }
    }
}
Traceback:
  File "telemetry_activity_logger.py", line 58, in _log_activity
    yield
  File "run.py", line 855, in _get_all_automl_child_runs
    raise AutoMLException._with_error(AzureMLError.create(ModelMissing, target="metric", metric=metric))

ExceptionTarget: metric
2024-01-08 09:15:10.664 - INFO - 36995 - azureml.train.automl.run._log_activity:89 - ActivityCompleted: Activity=GetChildren, HowEnded=Failure, Duration=406.61[ms]
2024-01-08 09:15:10.669 - CRITICAL - 36995 - azureml.train.automl.run.log_traceback:227 - Type: ModelMissing
Class: AutoMLException
Message: AutoMLException:
	Message: Could not find a model with valid score for metric 'accuracy'. Please ensure that at least one run was successfully completed with a valid score for the given metric.
	InnerException: None
	ErrorResponse 
{
    "error": {
        "code": "UserError",
        "message": "Could not find a model with valid score for metric 'accuracy'. Please ensure that at least one run was successfully completed with a valid score for the given metric.",
        "target": "metric",
        "inner_error": {
            "code": "NotFound",
            "inner_error": {
                "code": "ModelMissing"
            }
        }
    }
}
Traceback:
  File "telemetry_activity_logger.py", line 58, in _log_activity
    yield
  File "run.py", line 803, in _get_run_internal
    child_runs_and_scores = self._get_all_automl_child_runs(automl_settings.primary_metric)
  File "run.py", line 855, in _get_all_automl_child_runs
    raise AutoMLException._with_error(AzureMLError.create(ModelMissing, target="metric", metric=metric))

ExceptionTarget: metric
2024-01-08 09:15:10.674 - INFO - 36995 - azureml.train.automl.run._log_activity:89 - ActivityCompleted: Activity=GetChildren, HowEnded=Failure, Duration=483.92[ms]
2024-01-08 09:15:10.674 - CRITICAL - 36995 - azureml.train.automl.run.log_traceback:227 - Type: ModelMissing
Class: AutoMLException
Message: AutoMLException:
	Message: Could not find a model with valid score for metric 'accuracy'. Please ensure that at least one run was successfully completed with a valid score for the given metric.
	InnerException: None
	ErrorResponse 
{
    "error": {
        "code": "UserError",
        "message": "Could not find a model with valid score for metric 'accuracy'. Please ensure that at least one run was successfully completed with a valid score for the given metric.",
        "target": "metric",
        "inner_error": {
            "code": "NotFound",
            "inner_error": {
                "code": "ModelMissing"
            }
        }
    }
}
Traceback:
  File "telemetry_activity_logger.py", line 58, in _log_activity
    yield
  File "run.py", line 639, in _get_best_child_run
    curr_run = self._get_run_internal(iteration, metric, "get_output")
  File "run.py", line 803, in _get_run_internal
    child_runs_and_scores = self._get_all_automl_child_runs(automl_settings.primary_metric)
  File "run.py", line 855, in _get_all_automl_child_runs
    raise AutoMLException._with_error(AzureMLError.create(ModelMissing, target="metric", metric=metric))

ExceptionTarget: metric
2024-01-08 09:15:10.675 - INFO - 36995 - azureml.train.automl.run._log_activity:89 - ActivityCompleted: Activity=GetOutput, HowEnded=Failure, Duration=508.38[ms]
2024-01-08 09:15:10.675 - CRITICAL - 36995 - azureml.train.automl.run.log_traceback:227 - Type: ModelMissing
Class: AutoMLException
Message: AutoMLException:
	Message: Could not find a model with valid score for metric 'accuracy'. Please ensure that at least one run was successfully completed with a valid score for the given metric.
	InnerException: None
	ErrorResponse 
{
    "error": {
        "code": "UserError",
        "message": "Could not find a model with valid score for metric 'accuracy'. Please ensure that at least one run was successfully completed with a valid score for the given metric.",
        "target": "metric",
        "inner_error": {
            "code": "NotFound",
            "inner_error": {
                "code": "ModelMissing"
            }
        }
    }
}
Traceback:
  File "telemetry_activity_logger.py", line 58, in _log_activity
    yield
  File "run.py", line 707, in get_output
    curr_run, model_name = self._get_best_child_run(
  File "run.py", line 639, in _get_best_child_run
    curr_run = self._get_run_internal(iteration, metric, "get_output")
  File "run.py", line 803, in _get_run_internal
    child_runs_and_scores = self._get_all_automl_child_runs(automl_settings.primary_metric)
  File "run.py", line 855, in _get_all_automl_child_runs
    raise AutoMLException._with_error(AzureMLError.create(ModelMissing, target="metric", metric=metric))

ExceptionTarget: metric
2024-01-08 09:15:10.675 - INFO - 36995 - azureml.train.automl.run._log_activity:89 - ActivityCompleted: Activity=GetOutput, HowEnded=Failure, Duration=539.36[ms]
2024-01-08 09:35:24.674 - INFO - 37885 - azureml.train.automl.run._log_activity:55 - ActivityStarted: GetOutput
2024-01-08 09:35:24.713 - INFO - 37885 - azureml.train.automl.run._log_activity:55 - ActivityStarted: GetOutput
2024-01-08 09:35:24.726 - INFO - 37885 - azureml.train.automl.run._log_activity:55 - ActivityStarted: GetChildren
2024-01-08 09:35:24.900 - INFO - 37885 - azureml.train.automl.run._log_activity:89 - ActivityCompleted: Activity=GetChildren, HowEnded=Success, Duration=173.87[ms]
2024-01-08 09:35:24.973 - INFO - 37885 - azureml.train.automl.run._log_activity:89 - ActivityCompleted: Activity=GetOutput, HowEnded=Success, Duration=260.26[ms]
2024-01-08 09:35:24.980 - INFO - 37885 - azureml.train.automl._model_download_utilities._log_activity:55 - ActivityStarted: DownloadModel
2024-01-08 09:35:26.609 - INFO - 37885 - azureml.automl.runtime.featurization.data_transformer.__init__:190 - Feature sweeping enabled: False
2024-01-08 09:35:26.610 - INFO - 37885 - azureml.automl.runtime.featurization.data_transformer.__init__:191 - Feature sweeping timeout: 86400
2024-01-08 09:35:27.846 - INFO - 37885 - azureml.train.automl._model_download_utilities._log_activity:89 - ActivityCompleted: Activity=DownloadModel, HowEnded=Success, Duration=2866.17[ms]
2024-01-08 09:35:27.847 - INFO - 37885 - azureml.train.automl.run._log_activity:89 - ActivityCompleted: Activity=GetOutput, HowEnded=Success, Duration=3172.88[ms]
